// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reactProj.Models;

#nullable disable

namespace reactProj.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    partial class RecipeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("reactProj.Models.RecipeDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("totalTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("reactProj.Models.RecipeDetail+IngredientLines", b =>
                {
                    b.Property<string>("ingredients")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RecipeDetailid")
                        .HasColumnType("int");

                    b.HasKey("ingredients");

                    b.HasIndex("RecipeDetailid");

                    b.ToTable("IngredientLines");
                });

            modelBuilder.Entity("reactProj.Models.RecipeDetail+IngredientLines", b =>
                {
                    b.HasOne("reactProj.Models.RecipeDetail", null)
                        .WithMany("ingredientLines")
                        .HasForeignKey("RecipeDetailid");
                });

            modelBuilder.Entity("reactProj.Models.RecipeDetail", b =>
                {
                    b.Navigation("ingredientLines");
                });
#pragma warning restore 612, 618
        }
    }
}
